CREATE TABLE [dbo].[SAP_BASIC] (
    [SapBasicID]            INT             IDENTITY (1, 1) NOT NULL,
    [MemoNumber]            NVARCHAR (50)   CONSTRAINT [DF_SAP_BASIC_MemoNumber] DEFAULT ('') NOT NULL,
    [MemoDate]              DATETIME2 (7)   NOT NULL,
    [ItemDesc]              NVARCHAR (250)  NOT NULL,
    [ItemCode]              NVARCHAR (50)   NOT NULL,
    [ManufactureName]       NVARCHAR (250)  NULL,
    [ManufactureCode]       NVARCHAR (50)   NOT NULL,
    [SupplierName]          NVARCHAR (250)  NOT NULL,
    [SupplierCode]          NVARCHAR (50)   NOT NULL,
    [CustomerName]          NVARCHAR (250)  CONSTRAINT [DF_SAP_BASIC_CustomerName] DEFAULT ('') NOT NULL,
    [CustomerCode]          NVARCHAR (50)   CONSTRAINT [DF_SAP_BASIC_CustomerCode] DEFAULT ('') NOT NULL,
    [BatchNo]               NVARCHAR (50)   NOT NULL,
    [BatchQuantity]         DECIMAL (18, 2) NOT NULL,
    [BatchUOM]              NVARCHAR (50)   NOT NULL,
    [ManufactureDate]       DATETIME2 (7)   NOT NULL,
    [ExpiryDate]            DATETIME2 (7)   NOT NULL,
    [RetestDate]            DATETIME2 (7)   NOT NULL,
    [ExpiryRetestIndicator] NVARCHAR (250)  CONSTRAINT [DF__SAP_BASIC__Expir__2A4B4B5E] DEFAULT ('') NOT NULL,
    [SampleNo]              NVARCHAR (50)   NOT NULL,
    [SampleQty]             DECIMAL (18, 2) NOT NULL,
    [SampleQtyUOM]          NVARCHAR (50)   NOT NULL,
    [SamplingBy]            NVARCHAR (250)  NOT NULL,
    [InspectionType]        NVARCHAR (50)   NOT NULL,
    [PlantCode]             NVARCHAR (50)   NOT NULL,
    [CreatedBy]             NVARCHAR (250)  NOT NULL,
    [CreatedOn]             DATETIME2 (7)   NOT NULL,
    [TotalNoOfContainers]   INT             NOT NULL,
    [VendorBatchNo]         NVARCHAR (50)   NOT NULL,
    [InspectionLot]         NVARCHAR (50)   NOT NULL,
    [GRNNo]                 NVARCHAR (50)   NOT NULL,
    [GRNDate]               DATETIME2 (7)   NOT NULL,
    [GRNUOM]                NVARCHAR (50)   NOT NULL,
    [GRNQty]                DECIMAL (18, 2) NOT NULL,
    [NextInspInterval]      NVARCHAR (10)   CONSTRAINT [DF_SAP_BASIC_NextInspInterval] DEFAULT ('') NOT NULL,
    [RetestFlag]            TINYINT         CONSTRAINT [DF_SAP_BASIC_RetestFlag] DEFAULT ((0)) NOT NULL,
    [IsModified]            INT             CONSTRAINT [DF_SAP_BASIC_IsModified] DEFAULT ((0)) NULL,
    [InspReceiptId]         INT             CONSTRAINT [DF_SAP_BASIC_InspReceiptId] DEFAULT ((0)) NOT NULL,
    [DownloadedOn]          DATETIME2 (7)   NOT NULL,
    [VendorLotNo]           NVARCHAR (100)  CONSTRAINT [DF__SAP_BASIC__Vendo__48CFD27E] DEFAULT ('') NOT NULL,
    [BatchStorageLoc]       NVARCHAR (10)   DEFAULT ('') NULL,
    [PurchaseDocNum]        NVARCHAR (50)   DEFAULT ('') NULL,
    [MaterialType]          NVARCHAR (20)   DEFAULT ('') NULL,
    [DeliveryNote]          NVARCHAR (20)   DEFAULT ('') NULL,
    [ParentBatchNo]         NVARCHAR (25)   DEFAULT ('') NULL,
    [PackingSize]           NVARCHAR (50)   DEFAULT ('') NULL,
    [IsReduceTestingLot]    TINYINT         DEFAULT ((0)) NULL,
    [IsSkipLot]             TINYINT         DEFAULT ((0)) NULL,
    [InspectionLotDesc]     NVARCHAR (250)  DEFAULT ('') NULL,
    [InspEndDate]           DATETIME2 (7)   DEFAULT ('') NULL,
    [InspStartDate]         DATETIME2 (7)   DEFAULT ('') NULL,
    [InspectionLotOrigin]   NVARCHAR (10)   DEFAULT ('') NULL,
    [OperationNumber]       NVARCHAR (10)   DEFAULT ('') NULL,
    [RecordType]            NVARCHAR (10)   DEFAULT ('') NULL,
    CONSTRAINT [PK__SAP_BASI__8777EEDE1C88EECE] PRIMARY KEY CLUSTERED ([SapBasicID] ASC),
    CONSTRAINT [UQ__SAP_BASI__899A083598D3AEFD] UNIQUE NONCLUSTERED ([InspectionLot] ASC)
);

